# ===============================
# DATABASE CONNECTION SETTINGS
# ===============================
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/aptisphere_db?currentSchema=public
spring.datasource.username=apti_user
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE SETTINGS
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER SETTINGS
# ===============================
server.port=8000
jwt.expiration=86400000

# ===============================
# SECRETS IMPORT
# ===============================
# Pulls in passwords from the git-ignored file
spring.config.import=optional:classpath:application-secret.properties

# Expose all Actuator endpoints
management.endpoints.web.exposure.include=*

# Show Actuator endpoints in Swagger UI
springdoc.show-actuator=true

